// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5OZNjoaQpmF7wmyby5vvnGaoYtJvnOM',
    appId: '1:63640744288:android:959969fbbdc31e8183ae05',
    messagingSenderId: '63640744288',
    projectId: 'matajr-40a00',
    storageBucket: 'matajr-40a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNPGoa-ztCGDEnSDsh6tBVjaLgvz37rlc',
    appId: '1:63640744288:ios:348699a85084d1a683ae05',
    messagingSenderId: '63640744288',
    projectId: 'matajr-40a00',
    storageBucket: 'matajr-40a00.appspot.com',
    androidClientId: '63640744288-03mlijj18niva34fuundb1684jvkoh7h.apps.googleusercontent.com',
    iosClientId: '63640744288-goi9svb23cmjosg9lq5jda6qgtvk6r7s.apps.googleusercontent.com',
    iosBundleId: 'com.matajer.matajer',
  );

}